#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <string.h>

#include "general.h"
#include "net.h"
#include "training.h"
#include "allocation.h"


/********************************************************************************************************

*/
int setNetwork(netinfo * net, traininginfo * training, pattern * patternSet){
    int i;
    FOR(i,net->N){
        net->pat.unit[i]=patternSet->unit[i];
    }
    net->pat.unit[net->N]= net->ON;
    calcInputs(net);
    
    return stablePattern(net,&(net->pat));
}

/********************************************************************************************************
This function generates a net input distribution so that actual patterns can be generated by the generate patterns function

*/
int generateUnitInputsIndepenantActivation(netinfo * net, traininginfo * training){
    int i,pat;
    FOR(pat,training->maxLearntPatts){
        training->learntPatts[pat].num = pat;
        FOR(i,net->N){
            training->learntPatts[pat].unitInput[i] = nextRandomDouble()-(1-training->generateProbOn);
        }
    }
    return pat;
}

/********************************************************************************************************

*/
int generateUnitInputsExactActivationLevel(netinfo * net, traininginfo * training){
    int i,pat,unit;
    int * unitsOn=NULL;
    unitsOn = randomizeOrder(unitsOn,net->N);
    FOR(pat,training->maxLearntPatts){
        training->learntPatts[pat].num = pat;
        randomizeArray(unitsOn,net->N);
        FOR(i,net->N){
            training->learntPatts[pat].unitInput[i] = -1;
        }
        FOR(i,((int)net->N*training->generateProbOn)){
            unit = unitsOn[i];
            training->learntPatts[pat].unitInput[unit]= 1;
        }
    }
    free(unitsOn);
    return pat;
}


/********************************************************************************************************

*/
int generateUnitInputs(netinfo * net, traininginfo * training){
    if (training->generateActivationExactLevel)
        generateUnitInputsExactActivationLevel(net, training);
    else
        generateUnitInputsIndepenantActivation(net, training);
    return 1;
}

/********************************************************************************************************

*/
int generatePatterns(netinfo * net, traininginfo * training){
    int i,pat;
    int sum;
    FOR(pat,training->maxLearntPatts){
        sum =0;
        FOR(i,net->N){
            training->learntPatts[pat].unit[i] = activation(net,training->learntPatts[pat].unitInput[i]);
            if (training->learntPatts[pat].unit[i] == net->ON)
                sum++;
        }
        
        training->learntPatts[pat].unit[net->N] = net->ON;
        training->learntPatts[pat].sum = sum;
		training->learntPatts[pat].num = pat;
        
    }
    return sum;
}

int initAll(netinfo * net, traininginfo * training){
//    int to,from;

	memset(net->unitsToChange,0,net->N*sizeof(int));

    memset(net->unitOrder,0,net->N*sizeof(int));
    memset(net->noisyInput,0,net->N*sizeof(double));
    memset(net->weightArray,0,net->N*(net->N+1)*sizeof(double));
    memset(net->weightDeltaArray,0,net->N*(net->N+1)*sizeof(double));

	initPatternMemory(net, training);
    initPattern(net,&(net->pat));
    initPattern(net,&(net->initPat));
    initPattern(net,&(net->noisyPat));

    return 1;


}

void knuthShuffle(int * callSequence,int size)
{
	int temp;
	int newPos;
	int i;
	for (i = 0; i< size; i++)
	{
		newPos = RandomInt(i,size-1);
		temp = callSequence[i];
		callSequence[i] = callSequence[newPos];
		callSequence[newPos]=temp;
	}
}

void initSequence(int * callSequence,int size)
{
	int i;
	for ( i = 0; i< size; i++)
	{
		callSequence[i]=i;
	}
}


